-- MySQL Script generated by MySQL Workbench
-- 01/10/16 19:47:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema lab5_development
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lab5_development
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab5_development` DEFAULT CHARACTER SET utf8 ;
USE `lab5_development` ;

-- -----------------------------------------------------
-- Table `lab5_development`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5_development`.`friends` (
  `user_id` INT(11) NOT NULL,
  `friend_id` INT(11) NOT NULL,
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab5_development`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5_development`.`groups` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `owner_id` INT(11) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab5_development`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5_development`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NULL DEFAULT NULL,
  `password_digest` VARCHAR(1255) NULL DEFAULT NULL,
  `admin` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab5_development`.`microposts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5_development`.`microposts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `group_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_microposts_on_user_id` (`user_id` ASC),
  CONSTRAINT `fk_rails_558c81314b`
    FOREIGN KEY (`user_id`)
    REFERENCES `lab5_development`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 71
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `lab5_development`.`schema_migrations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab5_development`.`schema_migrations` (
  `version` VARCHAR(255) NOT NULL,
  UNIQUE INDEX `unique_schema_migrations` (`version` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
